INSERT INTO region(numregion,nom) VALUES (01,'Guadeloupe');
INSERT INTO region(numregion,nom) VALUES (02,'Martinique');
INSERT INTO region(numregion,nom) VALUES (03,'Guyane');
INSERT INTO region(numregion,nom) VALUES (04,'La Réunion');
INSERT INTO region(numregion,nom) VALUES (06,'Mayotte');
INSERT INTO region(numregion,nom) VALUES (11,'Île-de-France');
INSERT INTO region(numregion,nom) VALUES (24,'Centre-Val de Loire');
INSERT INTO region(numregion,nom) VALUES (27,'Bourgogne-Franche-Comté');
INSERT INTO region(numregion,nom) VALUES (28,'Normandie');
INSERT INTO region(numregion,nom) VALUES (32,'Hauts-de-France');
INSERT INTO region(numregion,nom) VALUES (44,'Grand Est');
INSERT INTO region(numregion,nom) VALUES (52,'Pays de la Loire');
INSERT INTO region(numregion,nom) VALUES (53,'Bretagne');
INSERT INTO region(numregion,nom) VALUES (75,'Nouvelle-Aquitaine');
INSERT INTO region(numregion,nom) VALUES (76,'Occitanie');
INSERT INTO region(numregion,nom) VALUES (84,'Auvergne-Rhône-Alpes');
INSERT INTO region(numregion,nom) VALUES (93,'Provence-Alpes-Côte d''Azur');
INSERT INTO region(numregion,nom) VALUES (94,'Corse');